(()=>{"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const canvas=$("#canvas"),ctx=canvas.getContext("2d"),state={width:1080,height:1080,bg:"#ffffff",zoom:1,objects:[],selected:null,selectedIds:[],tool:"select",history:[],future:[],drag:null,nextId:1,guides:[]};
const AUTOSAVE_KEY="ugd-autosave-v3";
function uid(){return"obj_"+state.nextId++}function clone(o){return JSON.parse(JSON.stringify(o))}function serialObject(o){const c=clone(o);delete c.image;return c}function snap(){return JSON.stringify({version:3,width:state.width,height:state.height,bg:state.bg,objects:state.objects.map(serialObject)})}
function commit(){state.history.push(snap());if(state.history.length>60)state.history.shift();state.future=[];historyButtons()}
function hydrateObject(o){if(!o||o.type!=="image"||!o.src)return o;const im=new Image;im.onload=()=>render();im.onerror=()=>render();im.src=o.src;o.image=im;return o}function hydrateAll(list){return(list||[]).map(o=>hydrateObject(Object.assign({opacity:1,visible:true,locked:false},o)))}
function restore(s){try{const d=JSON.parse(s);Object.assign(state,{width:Number(d.width)||1080,height:Number(d.height)||1080,bg:d.bg||"#fff",objects:hydrateAll(d.objects),selected:null,selectedIds:[],drag:null,guides:[]});state.nextId=Math.max(1,...state.objects.map(o=>Number(String(o.id||"").replace("obj_",""))||0))+1;resize();render();ui()}catch(e){console.warn(e)}}
function undo(){if(!state.history.length)return;state.future.push(snap());restore(state.history.pop())}function redo(){if(!state.future.length)return;state.history.push(snap());restore(state.future.pop())}
function resize(){canvas.width=state.width;canvas.height=state.height;canvas.style.width=state.width*state.zoom+"px";canvas.style.height=state.height*state.zoom+"px";$("#sizeLabel").textContent=state.width+" × "+state.height;$("#bgColor").value=state.bg}
function zoom(z){state.zoom=Math.max(.25,Math.min(2,Number(z)||1));canvas.style.width=state.width*state.zoom+"px";canvas.style.height=state.height*state.zoom+"px";$("#zoom").value=Math.round(state.zoom*100);$("#zoomLabel").textContent=Math.round(state.zoom*100)+"%";render()}
function fit(){const a=$("#canvasScroll"),z=Math.min((a.clientWidth-36)/state.width,(a.clientHeight-36)/state.height);zoom(Math.max(.25,Math.min(2,z)))}
function roundRect(x,y,w,h,r){const q=Math.min(Math.max(0,r),Math.abs(w)/2,Math.abs(h)/2);ctx.beginPath();ctx.moveTo(x+q,y);ctx.arcTo(x+w,y,x+w,y+h,q);ctx.arcTo(x+w,y+h,x,y+h,q);ctx.arcTo(x,y+h,x,y,q);ctx.arcTo(x,y,x+w,y,q);ctx.closePath()}
function textWidth(s,spacing){let n=0;for(const ch of String(s))n+=ctx.measureText(ch).width;return n+Math.max(0,String(s).length-1)*spacing}
function drawSpaced(text,x,y,spacing){if(!spacing){ctx.fillText(text,x,y);return}let start=x,total=textWidth(text,spacing);if(ctx.textAlign==="center")start-=total/2;else if(ctx.textAlign==="right")start-=total;for(const ch of String(text)){ctx.fillText(ch,start,y);start+=ctx.measureText(ch).width+spacing}}
function wrapText(t,w,lh,spacing){const words=String(t||"").split(/\s+/),lines=[];let line="";for(const word of words){const test=line?line+" "+word:word;if(textWidth(test,spacing)>w&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);const x=ctx.textAlign==="left"?-w/2:ctx.textAlign==="right"?w/2:0,y0=-(lines.length-1)*lh/2;lines.forEach((l,i)=>drawSpaced(l,x,y0+i*lh,spacing))}
function draw(o){if(o.visible===false)return;ctx.save();ctx.globalAlpha=Math.max(0,Math.min(1,o.opacity??1));ctx.translate(o.x,o.y);ctx.rotate((o.rotation||0)*Math.PI/180);if(o.type==="rect"){ctx.fillStyle=o.fill||"#7c5cff";roundRect(-o.w/2,-o.h/2,o.w,o.h,o.radius||0);ctx.fill();if(o.strokeWidth){ctx.strokeStyle=o.stroke||"#000";ctx.lineWidth=o.strokeWidth;ctx.stroke()}}if(o.type==="circle"){ctx.fillStyle=o.fill||"#ff6f91";ctx.beginPath();ctx.ellipse(0,0,o.w/2,o.h/2,0,0,Math.PI*2);ctx.fill();if(o.strokeWidth){ctx.strokeStyle=o.stroke||"#000";ctx.lineWidth=o.strokeWidth;ctx.stroke()}}if(o.type==="line"){ctx.strokeStyle=o.stroke||o.fill||"#17131f";ctx.lineWidth=o.strokeWidth||8;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(-o.w/2,0);ctx.lineTo(o.w/2,0);ctx.stroke()}if(o.type==="text"){ctx.fillStyle=o.fill||"#17131f";ctx.font=(o.italic?"italic ":"")+(o.weight||700)+" "+(o.fontSize||64)+"px "+(o.fontFamily||"system-ui");ctx.textAlign=o.align||"center";ctx.textBaseline="middle";wrapText(o.text,o.w,(o.fontSize||64)*(o.lineHeight||1.18),Number(o.letterSpacing)||0)}if(o.type==="image"&&o.image?.complete&&o.image.naturalWidth){ctx.filter=o.filter||"none";const iw=o.image.naturalWidth,ih=o.image.naturalHeight;if(o.fit==="contain"){const q=Math.min(o.w/iw,o.h/ih);ctx.drawImage(o.image,-iw*q/2,-ih*q/2,iw*q,ih*q)}else ctx.drawImage(o.image,-o.w/2,-o.h/2,o.w,o.h);ctx.filter="none"}ctx.restore()}
function renderGuides(){ctx.save();ctx.strokeStyle="#00b8ff";ctx.lineWidth=2/state.zoom;ctx.setLineDash([8/state.zoom,8/state.zoom]);for(const g of state.guides){ctx.beginPath();if(g.axis==="x"){ctx.moveTo(g.value,0);ctx.lineTo(g.value,state.height)}else{ctx.moveTo(0,g.value);ctx.lineTo(state.width,g.value)}ctx.stroke()}ctx.restore()}
function render(){ctx.clearRect(0,0,state.width,state.height);ctx.fillStyle=state.bg;ctx.fillRect(0,0,state.width,state.height);state.objects.forEach(draw);renderGuides();const ids=state.selectedIds.length?state.selectedIds:state.selected?[state.selected]:[];ids.map(id=>state.objects.find(o=>o.id===id)).filter(Boolean).forEach(o=>{ctx.save();ctx.translate(o.x,o.y);ctx.rotate((o.rotation||0)*Math.PI/180);ctx.strokeStyle="#7c5cff";ctx.lineWidth=3/state.zoom;ctx.setLineDash([10/state.zoom,6/state.zoom]);ctx.strokeRect(-o.w/2,-o.h/2,o.w,o.h);ctx.setLineDash([]);ctx.restore()});const o=state.objects.find(x=>x.id===state.selected);if(o&&state.selectedIds.length<=1&&!o.locked){ctx.save();ctx.translate(o.x,o.y);ctx.rotate((o.rotation||0)*Math.PI/180);ctx.fillStyle="#fff";ctx.strokeStyle="#7c5cff";ctx.lineWidth=2/state.zoom;for(const [x,y] of [[-o.w/2,-o.h/2],[o.w/2,-o.h/2],[o.w/2,o.h/2],[-o.w/2,o.h/2]]){ctx.beginPath();ctx.arc(x,y,12/state.zoom,0,Math.PI*2);ctx.fill();ctx.stroke()}ctx.beginPath();ctx.moveTo(0,-o.h/2);ctx.lineTo(0,-o.h/2-42/state.zoom);ctx.stroke();ctx.beginPath();ctx.arc(0,-o.h/2-50/state.zoom,9/state.zoom,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()}$("#emptyHint").hidden=state.objects.length>0}
function localPoint(o,x,y){const a=-(o.rotation||0)*Math.PI/180,dx=x-o.x,dy=y-o.y;return{x:dx*Math.cos(a)-dy*Math.sin(a),y:dx*Math.sin(a)+dy*Math.cos(a)}}function handleAt(o,x,y){const p=localPoint(o,x,y),m=18/state.zoom;if(Math.abs(p.x-o.w/2)<m&&Math.abs(p.y-o.h/2)<m)return"se";if(Math.abs(p.x+o.w/2)<m&&Math.abs(p.y-o.h/2)<m)return"sw";if(Math.abs(p.x-o.w/2)<m&&Math.abs(p.y+o.h/2)<m)return"ne";if(Math.abs(p.x+o.w/2)<m&&Math.abs(p.y+o.h/2)<m)return"nw";if(Math.abs(p.x)<m&&Math.abs(p.y+o.h/2)<m)return"n";if(Math.abs(p.x)<m&&Math.abs(p.y-o.h/2)<m)return"s";if(Math.abs(p.x-o.w/2)<m&&Math.abs(p.y)<m)return"e";if(Math.abs(p.x+o.w/2)<m&&Math.abs(p.y)<m)return"w";if(Math.abs(p.x)<m&&Math.abs(p.y+o.h/2+50/state.zoom)<m)return"rotate";return null}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*state.width/r.width,y:(e.clientY-r.top)*state.height/r.height}}function hit(o,x,y){if(o.visible===false)return false;const p=localPoint(o,x,y);if(o.type==="circle")return(p.x/(o.w/2))**2+(p.y/(o.h/2))**2<=1;return Math.abs(p.x)<=o.w/2&&Math.abs(p.y)<=o.h/2}
function base(type,x,y){return{id:uid(),type,x,y,w:300,h:180,rotation:0,opacity:1,fill:"#7c5cff",stroke:"#000",strokeWidth:0,radius:24,visible:true,locked:false}}
function select(x,y,additive=false){for(let i=state.objects.length-1;i>=0;i--){const o=state.objects[i];if(o.locked||!hit(o,x,y))continue;const members=o.groupId?state.objects.filter(q=>q.groupId===o.groupId).map(q=>q.id):[o.id];if(additive){const has=state.selectedIds.includes(o.id);state.selectedIds=has?state.selectedIds.filter(v=>!members.includes(v)):[...new Set([...state.selectedIds,...members])];state.selected=state.selectedIds.at(-1)||null}else{state.selected=o.id;state.selectedIds=members}render();ui();return}if(!additive){state.selected=null;state.selectedIds=[];render();ui()}}
function add(x,y){if(state.tool==="select"){select(x,y);return}if(state.tool==="image"){$("#imageInput").click();return}const o=base(state.tool,x,y);if(state.tool==="text")Object.assign(o,{w:430,h:120,text:"Your text",fontSize:64,fontFamily:"system-ui",weight:750,italic:false,lineHeight:1.18,letterSpacing:0,align:"center",fill:"#17131f"});if(state.tool==="circle"){o.w=o.h=190;o.fill="#ff6f91"}if(state.tool==="line"){o.w=360;o.h=10;o.fill="#17131f";o.stroke="#17131f";o.strokeWidth=10}commit();state.objects.push(o);state.selected=o.id;state.selectedIds=[o.id];state.tool="select";active();render();ui();autosave()}
function active(){$$(".tool").forEach(b=>b.classList.toggle("active",b.dataset.tool===state.tool))}function name(o){return o.type==="text"?String(o.text||"").slice(0,24)||"Text":o.type[0].toUpperCase()+o.type.slice(1)}function esc(s){return String(s).replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c]))}
function ui(){props();layers();$("#deleteSelected").disabled=!state.selectedIds.length;$("#duplicateSelected").disabled=!state.selectedIds.length;$("#groupSelected").disabled=state.selectedIds.length<2;$("#ungroupSelected").disabled=!selectedObjects().some(o=>o.groupId);historyButtons();$("#status").textContent=state.selectedIds.length>1?state.selectedIds.length+" objects selected":state.selected?"Object selected":"Select an object or choose a tool."}
function props(){const h=$("#properties"),o=state.objects.find(x=>x.id===state.selected);if(!o){h.innerHTML='<div class="empty-state">Select an object to edit its properties.</div>';return}let s='<div class="prop-grid"><div class="prop"><label>X</label><input data-p="x" type="number" value="'+Math.round(o.x)+'"></div><div class="prop"><label>Y</label><input data-p="y" type="number" value="'+Math.round(o.y)+'"></div><div class="prop"><label>Width</label><input data-p="w" type="number" min="1" value="'+Math.round(o.w)+'"></div><div class="prop"><label>Height</label><input data-p="h" type="number" min="1" value="'+Math.round(o.h)+'"></div><div class="prop"><label>Rotation</label><input data-p="rotation" type="number" value="'+Math.round(o.rotation||0)+'"></div><div class="prop"><label>Opacity</label><input data-p="opacity" type="number" min="0" max="1" step=".05" value="'+(o.opacity??1)+'"></div></div>';
if(o.type==="text")s+='<div class="prop"><label>Text</label><textarea class="text-area" data-p="text">'+esc(o.text||"")+'</textarea></div><div class="prop-grid"><div class="prop"><label>Font</label><select data-p="fontFamily"><option>system-ui</option><option>Arial</option><option>Georgia</option><option>Verdana</option><option>Trebuchet MS</option><option>Courier New</option></select></div><div class="prop"><label>Font size</label><input data-p="fontSize" type="number" min="8" value="'+o.fontSize+'"></div><div class="prop"><label>Weight</label><select data-p="weight"><option value="400">Regular</option><option value="600">Semibold</option><option value="750">Bold</option><option value="900">Black</option></select></div><div class="prop"><label>Style</label><select data-p="italic"><option value="false">Normal</option><option value="true">Italic</option></select></div><div class="prop"><label>Align</label><select data-p="align"><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></div><div class="prop"><label>Line height</label><input data-p="lineHeight" type="number" min=".8" max="3" step=".05" value="'+(o.lineHeight||1.18)+'"></div><div class="prop"><label>Letter spacing</label><input data-p="letterSpacing" type="number" step=".5" value="'+(o.letterSpacing||0)+'"></div><div class="prop wide"><label>Text color</label><input data-p="fill" type="color" value="'+(o.fill||"#17131f")+'"></div></div>';
else if(o.type==="image")s+='<div class="prop-grid"><div class="prop wide"><label>Image fit</label><select data-p="fit"><option value="fill">Fill</option><option value="contain">Contain</option></select></div><div class="prop wide"><label>Filter</label><select data-p="filter"><option value="none">Original</option><option value="grayscale(1)">Grayscale</option><option value="sepia(1)">Sepia</option><option value="contrast(1.25)">High contrast</option><option value="brightness(1.2)">Bright</option></select></div></div>';
else if(o.type==="line")s+='<div class="prop-grid"><div class="prop"><label>Color</label><input data-p="stroke" type="color" value="'+(o.stroke||o.fill)+'"></div><div class="prop"><label>Thickness</label><input data-p="strokeWidth" type="number" min="1" value="'+o.strokeWidth+'"></div></div>';
else s+='<div class="prop-grid"><div class="prop"><label>Fill</label><input data-p="fill" type="color" value="'+(o.fill||"#7c5cff")+'"></div><div class="prop"><label>Radius</label><input data-p="radius" type="number" min="0" value="'+(o.radius||0)+'"></div><div class="prop"><label>Stroke</label><input data-p="stroke" type="color" value="'+(o.stroke||"#000000")+'"></div><div class="prop"><label>Stroke width</label><input data-p="strokeWidth" type="number" min="0" value="'+(o.strokeWidth||0)+'"></div></div>';
s+='<div class="prop-grid"><div class="prop"><label>Visibility</label><select data-p="visible"><option value="true">Visible</option><option value="false">Hidden</option></select></div><div class="prop"><label>Lock</label><select data-p="locked"><option value="false">Unlocked</option><option value="true">Locked</option></select></div></div>';h.innerHTML=s;const w=h.querySelector('[data-p="weight"]');if(w)w.value=o.weight;const it=h.querySelector('[data-p="italic"]');if(it)it.value=String(!!o.italic);const al=h.querySelector('[data-p="align"]');if(al)al.value=o.align||"center";const ff=h.querySelector('[data-p="fontFamily"]');if(ff)ff.value=o.fontFamily||"system-ui";const vi=h.querySelector('[data-p="visible"]');if(vi)vi.value=String(o.visible!==false);const lo=h.querySelector('[data-p="locked"]');if(lo)lo.value=String(!!o.locked);h.querySelectorAll("[data-p]").forEach(el=>el.onchange=()=>{let v=el.value;if(["x","y","w","h","rotation","opacity","fontSize","strokeWidth","radius","weight","lineHeight","letterSpacing"].includes(el.dataset.p))v=Number(v);if(["visible","locked","italic"].includes(el.dataset.p))v=v==="true";commit();o[el.dataset.p]=v;render();ui();autosave()})}
function layers(){const h=$("#layers");h.innerHTML="";[...state.objects].reverse().forEach(o=>{const r=document.createElement("div");r.className="layer"+(state.selectedIds.includes(o.id)?" selected":"");r.innerHTML='<span class="layer-icon">'+(o.type==="text"?"T":o.type==="image"?"▧":o.type==="circle"?"●":"▰")+'</span><span class="layer-name"></span><button title="Visibility">'+(o.visible===false?"◌":"◉")+'</button><button title="Lock">'+(o.locked?"🔒":"🔓")+'</button><button title="Move up">↑</button><button title="Move down">↓</button>';r.querySelector(".layer-name").textContent=(o.groupId?"▧ ":"")+name(o);r.onclick=e=>{if(e.target.tagName!=="BUTTON"){const ids=o.groupId?state.objects.filter(q=>q.groupId===o.groupId).map(q=>q.id):[o.id];state.selected=o.id;state.selectedIds=ids;render();ui()}};const b=r.querySelectorAll("button");b[0].onclick=e=>{e.stopPropagation();commit();o.visible=o.visible===false;render();ui();autosave()};b[1].onclick=e=>{e.stopPropagation();commit();o.locked=!o.locked;render();ui();autosave()};b[2].onclick=e=>{e.stopPropagation();move(o.id,1)};b[3].onclick=e=>{e.stopPropagation();move(o.id,-1)};h.appendChild(r)})}
function move(id,dir){const i=state.objects.findIndex(o=>o.id===id),j=i+dir;if(i<0||j<0||j>=state.objects.length)return;commit();[state.objects[i],state.objects[j]]=[state.objects[j],state.objects[i]];render();ui();autosave()}
function selectedObjects(){return state.objects.filter(o=>state.selectedIds.includes(o.id))}function groupSelected(){const a=selectedObjects();if(a.length<2)return;commit();const id="group_"+Date.now().toString(36)+"_"+Math.random().toString(36).slice(2,7);a.forEach(o=>o.groupId=id);render();ui();autosave()}function ungroupSelected(){const a=selectedObjects();const groups=[...new Set(a.map(o=>o.groupId).filter(Boolean))];if(!groups.length)return;commit();state.objects.forEach(o=>{if(groups.includes(o.groupId))delete o.groupId});render();ui();autosave()}function align(mode){const a=selectedObjects();if(!a.length)return;commit();if(mode==="left")a.forEach(o=>o.x=Math.min(...a.map(q=>q.x-q.w/2))+o.w/2);if(mode==="center")a.forEach(o=>o.x=(Math.min(...a.map(q=>q.x-q.w/2))+Math.max(...a.map(q=>q.x+q.w/2)))/2);if(mode==="right")a.forEach(o=>o.x=Math.max(...a.map(q=>q.x+q.w/2))-o.w/2);if(mode==="top")a.forEach(o=>o.y=Math.min(...a.map(q=>q.y-q.h/2))+o.h/2);if(mode==="middle")a.forEach(o=>o.y=(Math.min(...a.map(q=>q.y-q.h/2))+Math.max(...a.map(q=>q.y+q.h/2)))/2);if(mode==="bottom")a.forEach(o=>o.y=Math.max(...a.map(q=>q.y+q.h/2))-o.h/2);render();ui();autosave()}
function centerSelected(){const a=selectedObjects();if(!a.length)return;commit();a.forEach(o=>{o.x=state.width/2;o.y=state.height/2});render();ui();autosave()}
function snapMove(o,x,y){const t=8;state.guides=[];if(Math.abs(x-state.width/2)<t){x=state.width/2;state.guides.push({axis:"x",value:x})}if(Math.abs(y-state.height/2)<t){y=state.height/2;state.guides.push({axis:"y",value:y})}for(const q of state.objects){if(q.id===o.id||q.visible===false)continue;if(Math.abs(x-q.x)<t){x=q.x;state.guides.push({axis:"x",value:x})}if(Math.abs(y-q.y)<t){y=q.y;state.guides.push({axis:"y",value:y})}}return{x,y}}
function nudge(dx,dy){const a=selectedObjects().filter(o=>!o.locked);if(!a.length)return;commit();a.forEach(o=>{o.x+=dx;o.y+=dy});render();ui();autosave()}
function duplicate(){const a=selectedObjects();if(!a.length)return;commit();const made=a.map(o=>{const c=serialObject(o);c.id=uid();c.x+=24;c.y+=24;return hydrateObject(c)});state.objects.push(...made);state.selectedIds=made.map(o=>o.id);state.selected=made.at(-1).id;render();ui();autosave()}
function del(){const ids=new Set(state.selectedIds);if(!ids.size)return;commit();state.objects=state.objects.filter(o=>!ids.has(o.id));state.selected=null;state.selectedIds=[];render();ui();autosave()}
function copy(){const a=selectedObjects();if(a.length)navigator.clipboard?.writeText(JSON.stringify(a.map(serialObject))).catch(()=>{})}async function paste(){try{const a=JSON.parse(await navigator.clipboard.readText());if(!Array.isArray(a)||!a.length)return;commit();const made=a.map(o=>hydrateObject(Object.assign({},o,{id:uid(),x:(o.x||0)+30,y:(o.y||0)+30})));state.objects.push(...made);state.selectedIds=made.map(o=>o.id);state.selected=made.at(-1).id;render();ui();autosave()}catch(e){}}
function historyButtons(){$("#undo").disabled=!state.history.length;$("#redo").disabled=!state.future.length}function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function project(){return{app:"Universal Graphics Designer",version:3,width:state.width,height:state.height,bg:state.bg,objects:state.objects.map(serialObject)}}function exportPNG(){canvas.toBlob(b=>download(b,"universal-graphics-design.png"),"image/png")}
function exportSVG(){const E=s=>String(s).replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c]));const p=[`<svg xmlns="http://www.w3.org/2000/svg" width="${state.width}" height="${state.height}" viewBox="0 0 ${state.width} ${state.height}"><rect width="100%" height="100%" fill="${state.bg}"/>`];for(const o of state.objects){if(o.visible===false)continue;const tr=`translate(${o.x} ${o.y}) rotate(${o.rotation||0})`,op=o.opacity??1;if(o.type==="rect")p.push(`<rect x="${-o.w/2}" y="${-o.h/2}" width="${o.w}" height="${o.h}" rx="${o.radius||0}" fill="${o.fill}" stroke="${o.stroke||"none"}" stroke-width="${o.strokeWidth||0}" opacity="${op}" transform="${tr}"/>`);else if(o.type==="circle")p.push(`<ellipse rx="${o.w/2}" ry="${o.h/2}" fill="${o.fill}" stroke="${o.stroke||"none"}" stroke-width="${o.strokeWidth||0}" opacity="${op}" transform="${tr}"/>`);else if(o.type==="line")p.push(`<line x1="${-o.w/2}" x2="${o.w/2}" y1="0" y2="0" stroke="${o.stroke||o.fill}" stroke-width="${o.strokeWidth||8}" stroke-linecap="round" opacity="${op}" transform="${tr}"/>`);else if(o.type==="text")p.push(`<text x="${o.align==="left"?-o.w/2:o.align==="right"?o.w/2:0}" y="0" text-anchor="${o.align==="left"?"start":o.align==="right"?"end":"middle"}" dominant-baseline="middle" font-family="${E(o.fontFamily||"system-ui")}" font-size="${o.fontSize||64}" font-weight="${o.weight||700}" font-style="${o.italic?"italic":"normal"}" letter-spacing="${o.letterSpacing||0}px" fill="${o.fill}" opacity="${op}" transform="${tr}">${E(o.text||"")}</text>`);else if(o.type==="image"&&o.src)p.push(`<image href="${o.src}" x="${-o.w/2}" y="${-o.h/2}" width="${o.w}" height="${o.h}" preserveAspectRatio="${o.fit==="contain"?"xMidYMid meet":"none"}" opacity="${op}" transform="${tr}"/>`)}p.push("</svg>");download(new Blob([p.join("")],{type:"image/svg+xml"}),"universal-graphics-design.svg")}
function exportProject(){download(new Blob([JSON.stringify(project(),null,2)],{type:"application/json"}),"universal-graphics-project.json")}
function autosave(){try{localStorage.setItem(AUTOSAVE_KEY,JSON.stringify(project()))}catch(e){console.warn("Autosave unavailable",e)}}
function importProject(data){if(!data||data.app!=="Universal Graphics Designer"||!Array.isArray(data.objects))throw Error("Invalid project");commit();state.width=Number(data.width)||1080;state.height=Number(data.height)||1080;state.bg=data.bg||"#fff";state.objects=hydrateAll(data.objects);state.selected=null;state.selectedIds=[];state.nextId=Math.max(1,...state.objects.map(o=>Number(String(o.id||"").replace("obj_",""))||0))+1;resize();render();ui();autosave()}
canvas.addEventListener("pointerdown",e=>{const p=point(e);if(state.tool!=="select"){add(p.x,p.y);return}const o=[...state.objects].reverse().find(q=>!q.locked&&hit(q,p.x,p.y));if(!o){select(p.x,p.y,e.shiftKey);return}if(e.shiftKey)select(p.x,p.y,true);else if(!state.selectedIds.includes(o.id))select(p.x,p.y,false);const activeO=state.objects.find(q=>q.id===state.selected);const h=activeO&&state.selectedIds.length<=1?handleAt(activeO,p.x,p.y):null;const ids=state.selectedIds.length?state.selectedIds:[activeO.id];state.drag={mode:h||"move",start:p,object:activeO,orig:activeO?{x:activeO.x,y:activeO.y,w:activeO.w,h:activeO.h,r:activeO.rotation||0}:null,starts:state.objects.filter(q=>ids.includes(q.id)).map(q=>({id:q.id,x:q.x,y:q.y}))};canvas.setPointerCapture?.(e.pointerId)});
canvas.addEventListener("pointermove",e=>{if(!state.drag)return;const p=point(e),d=state.drag,o=d.object;if(!o)return;const dx=p.x-d.start.x,dy=p.y-d.start.y;if(d.mode==="move"){d.starts.forEach(s=>{const q=state.objects.find(v=>v.id===s.id);if(q&&!q.locked){q.x=s.x+dx;q.y=s.y+dy}});if(d.starts.length===1){const q=snapMove(o,o.x,o.y);o.x=q.x;o.y=q.y}}else if(d.mode==="rotate"){o.rotation=d.orig.r+(Math.atan2(p.y-o.y,p.x-o.x)-Math.atan2(d.start.y-o.y,d.start.x-o.x))*180/Math.PI}else{const lp=localPoint(o,p.x,p.y),op=localPoint(o,d.start.x,d.start.y),lx=lp.x-op.x,ly=lp.y-op.y;if(d.mode.includes("e"))o.w=Math.max(20,d.orig.w+lx);if(d.mode.includes("w")){o.w=Math.max(20,d.orig.w-lx);o.x=d.orig.x+lx/2}if(d.mode.includes("s"))o.h=Math.max(20,d.orig.h+ly);if(d.mode.includes("n")){o.h=Math.max(20,d.orig.h-ly);o.y=d.orig.y+ly/2}}render()});
canvas.addEventListener("pointerup",e=>{if(state.drag){commit();autosave();state.drag=null;state.guides=[];render();ui()}try{canvas.releasePointerCapture(e.pointerId)}catch(_){} });canvas.addEventListener("dblclick",e=>{const p=point(e),o=[...state.objects].reverse().find(q=>q.type==="text"&&!q.locked&&hit(q,p.x,p.y));if(!o)return;const t=prompt("Edit text",o.text);if(t!==null&&t!==o.text){commit();o.text=t;render();ui();autosave()}});
$$(".tool").forEach(b=>b.onclick=()=>{state.tool=b.dataset.tool;active();if(state.tool==="image")$("#imageInput").click()});$("#undo").onclick=undo;$("#redo").onclick=redo;$("#zoomOut").onclick=()=>zoom(state.zoom-.1);$("#zoomIn").onclick=()=>zoom(state.zoom+.1);$("#fitCanvas").onclick=fit;$("#zoom").oninput=e=>zoom(Number(e.target.value)/100);$("#bgColor").onchange=e=>{commit();state.bg=e.target.value;render();autosave()};$("#clearAll").onclick=()=>{if(state.objects.length&&confirm("Clear the entire design?")){commit();state.objects=[];state.selected=null;state.selectedIds=[];render();ui();autosave()}};
$("#canvasSize").onchange=e=>{if(e.target.value==="custom"){const w=Number(prompt("Canvas width",state.width)),h=Number(prompt("Canvas height",state.height));if(w>0&&h>0){commit();state.width=Math.min(4000,w);state.height=Math.min(4000,h);resize();fit();render();autosave()}return}const [w,h]=e.target.value.split("x").map(Number);commit();state.width=w;state.height=h;resize();fit();render();autosave()};
$("#deleteSelected").onclick=del;$("#duplicateSelected").onclick=duplicate;$("#groupSelected").onclick=groupSelected;$("#ungroupSelected").onclick=ungroupSelected;$("#centerSelected").onclick=centerSelected;[["alignLeft","left"],["alignCenter","center"],["alignRight","right"],["alignTop","top"],["alignMiddle","middle"],["alignBottom","bottom"]].forEach(([id,m])=>$("#"+id).onclick=()=>align(m));
$("#imageInput").onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader;r.onload=()=>{const im=new Image;im.onload=()=>{const o=base("image",state.width/2,state.height/2),scale=Math.min(800/im.naturalWidth,600/im.naturalHeight,1);o.w=im.naturalWidth*scale;o.h=im.naturalHeight*scale;o.src=r.result;o.image=im;o.fit="contain";o.filter="none";commit();state.objects.push(o);state.selected=o.id;state.selectedIds=[o.id];state.tool="select";active();render();ui();autosave()};im.src=r.result};r.readAsDataURL(f);e.target.value=""};
$("#saveProject").onclick=exportProject;$("#openProject").onclick=()=>$("#projectInput").click();$("#projectInput").onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader;r.onload=()=>{try{importProject(JSON.parse(r.result))}catch(_){alert("That project file could not be opened.")}};r.readAsText(f);e.target.value=""};$("#exportBtn").onclick=()=>$("#exportDialog").showModal();$$("[data-export]").forEach(b=>b.onclick=()=>setTimeout(()=>b.dataset.export==="png"?exportPNG():b.dataset.export==="svg"?exportSVG():exportProject(),0));$("#helpBtn").onclick=()=>$("#helpDialog").showModal();$("#closeHelp").onclick=()=>$("#helpDialog").close();
$$("[data-template]").forEach(b=>b.onclick=()=>{const t=b.dataset.template;commit();state.objects=[];state.selected=null;state.selectedIds=[];if(t!=="blank"){const bg=base("rect",state.width/2,state.height/2);bg.w=state.width-80;bg.h=state.height-80;bg.fill=t==="poster"?"#17131f":t==="quote"?"#f4efe6":"#7c5cff";bg.radius=36;const tx=base("text",state.width/2,state.height/2);tx.w=state.width-180;tx.h=300;tx.text=t==="poster"?"MAKE IT UNIVERSAL":t==="quote"?"Create something worth sharing.":"BIG NEWS";tx.fontSize=82;tx.fill=t==="quote"?"#17131f":"#fff";state.objects=[bg,tx];state.selected=tx.id;state.selectedIds=[tx.id]}render();ui();autosave()});
window.addEventListener("keydown",e=>{const tag=document.activeElement?.tagName;if(tag==="INPUT"||tag==="TEXTAREA"||tag==="SELECT")return;const mod=e.ctrlKey||e.metaKey,k=e.key.toLowerCase();if(mod&&k==="z"){e.preventDefault();undo();return}if(mod&&k==="y"){e.preventDefault();redo();return}if(mod&&k==="d"){e.preventDefault();duplicate();return}if(mod&&k==="c"){e.preventDefault();copy();return}if(mod&&k==="v"){e.preventDefault();paste();return}if(k==="delete"||k==="backspace"){e.preventDefault();del();return}if(k==="escape"){state.selected=null;state.selectedIds=[];render();ui();return}if(e.key.startsWith("Arrow")){e.preventDefault();const d=e.shiftKey?10:1;nudge(e.key==="ArrowLeft"?-d:e.key==="ArrowRight"?d:0,e.key==="ArrowUp"?-d:e.key==="ArrowDown"?d:0);return}const m={v:"select",t:"text",r:"rect",c:"circle",i:"image"};if(m[k]){$(".tool[data-tool='"+m[k]+"']").click()}});
resize();active();ui();render();
})();