(()=>{"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const canvas=$("#canvas"),ctx=canvas.getContext("2d"),state={width:1080,height:1080,bg:"#ffffff",zoom:1,objects:[],selected:null,selectedIds:[],tool:"select",history:[],future:[],drag:null,nextId:1,guides:[]};
function uid(){return"obj_"+state.nextId++}function snap(){return JSON.stringify({width:state.width,height:state.height,bg:state.bg,objects:state.objects})}
function commit(){state.history.push(snap());if(state.history.length>60)state.history.shift();state.future=[];historyButtons()}
function restore(s){const d=JSON.parse(s);Object.assign(state,{width:d.width,height:d.height,bg:d.bg,objects:d.objects,selected:null,drag:null});resize();render();ui()}
function undo(){if(!state.history.length)return;state.future.push(snap());restore(state.history.pop())}function redo(){if(!state.future.length)return;state.history.push(snap());restore(state.future.pop())}
function resize(){canvas.width=state.width;canvas.height=state.height;canvas.style.width=state.width*state.zoom+"px";canvas.style.height=state.height*state.zoom+"px";$("#sizeLabel").textContent=state.width+" × "+state.height;$("#bgColor").value=state.bg}
function zoom(z){state.zoom=Math.max(.25,Math.min(2,Number(z)));canvas.style.width=state.width*state.zoom+"px";canvas.style.height=state.height*state.zoom+"px";$("#zoom").value=Math.round(state.zoom*100);$("#zoomLabel").textContent=Math.round(state.zoom*100)+"%"}
function fit(){const a=$("#canvasScroll"),z=Math.min((a.clientWidth-36)/state.width,(a.clientHeight-36)/state.height);zoom(Math.max(.25,Math.min(2,z)))}
function roundRect(x,y,w,h,r){const q=Math.min(r,Math.abs(w)/2,Math.abs(h)/2);ctx.beginPath();ctx.moveTo(x+q,y);ctx.arcTo(x+w,y,x+w,y+h,q);ctx.arcTo(x+w,y+h,x,y+h,q);ctx.arcTo(x,y+h,x,y,q);ctx.arcTo(x,y,x+w,y,q);ctx.closePath()}
function wrapText(t,w,lh){const words=String(t).split(/\s+/),lines=[];let line="";for(const word of words){const test=line?line+" "+word:word;if(ctx.measureText(test).width>w&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);lines.forEach((l,i)=>ctx.fillText(l,0,(i-(lines.length-1)/2)*lh))}
function draw(o){ctx.save();ctx.globalAlpha=o.opacity??1;ctx.translate(o.x,o.y);ctx.rotate((o.rotation||0)*Math.PI/180);
if(o.type==="rect"){ctx.fillStyle=o.fill;roundRect(-o.w/2,-o.h/2,o.w,o.h,o.radius||0);ctx.fill();if(o.strokeWidth){ctx.strokeStyle=o.stroke;ctx.lineWidth=o.strokeWidth;ctx.stroke()}}
if(o.type==="circle"){ctx.fillStyle=o.fill;ctx.beginPath();ctx.ellipse(0,0,o.w/2,o.h/2,0,0,Math.PI*2);ctx.fill();if(o.strokeWidth){ctx.strokeStyle=o.stroke;ctx.lineWidth=o.strokeWidth;ctx.stroke()}}
if(o.type==="line"){ctx.strokeStyle=o.stroke||o.fill;ctx.lineWidth=o.strokeWidth||8;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(-o.w/2,0);ctx.lineTo(o.w/2,0);ctx.stroke()}
if(o.type==="text"){ctx.fillStyle=o.fill;ctx.font=(o.italic?"italic ":"")+(o.weight||700)+" "+o.fontSize+"px "+o.fontFamily;ctx.textAlign=o.align||"center";ctx.textBaseline="middle";wrapText(o.text,o.w,o.fontSize*(o.lineHeight||1.18));}
if(o.type==="image"&&o.image?.complete){ctx.globalAlpha=o.opacity??1;ctx.filter=o.filter||"none";ctx.drawImage(o.image,-o.w/2,-o.h/2,o.w,o.h);ctx.filter="none";}ctx.restore()}
function renderGuides(){ctx.save();ctx.strokeStyle="#00b8ff";ctx.lineWidth=2/state.zoom;ctx.setLineDash([8/state.zoom,8/state.zoom]);for(const g of state.guides){ctx.beginPath();if(g.axis==="x"){ctx.moveTo(g.value,0);ctx.lineTo(g.value,state.height)}else{ctx.moveTo(0,g.value);ctx.lineTo(state.width,g.value)}ctx.stroke()}ctx.restore()}function render(){ctx.clearRect(0,0,state.width,state.height);ctx.fillStyle=state.bg;ctx.fillRect(0,0,state.width,state.height);state.objects.forEach(draw);renderGuides();const o=state.objects.find(x=>x.id===state.selected);$("#emptyHint").hidden=state.objects.length>0;if(o){ctx.save();ctx.translate(o.x,o.y);ctx.rotate((o.rotation||0)*Math.PI/180);ctx.strokeStyle="#7c5cff";ctx.lineWidth=3/state.zoom;ctx.setLineDash([10/state.zoom,6/state.zoom]);ctx.strokeRect(-o.w/2,-o.h/2,o.w,o.h);ctx.setLineDash([]);ctx.fillStyle="#fff";ctx.strokeStyle="#7c5cff";ctx.lineWidth=2/state.zoom;for(const [x,y] of [[-o.w/2,-o.h/2],[o.w/2,-o.h/2],[o.w/2,o.h/2],[-o.w/2,o.h/2]]){ctx.beginPath();ctx.arc(x,y,12/state.zoom,0,Math.PI*2);ctx.fill();ctx.stroke()}ctx.beginPath();ctx.moveTo(0,-o.h/2);ctx.lineTo(0,-o.h/2-42/state.zoom);ctx.stroke();ctx.beginPath();ctx.arc(0,-o.h/2-50/state.zoom,9/state.zoom,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()}}
function localPoint(o,x,y){const a=-(o.rotation||0)*Math.PI/180,dx=x-o.x,dy=y-o.y;return{x:dx*Math.cos(a)-dy*Math.sin(a),y:dx*Math.sin(a)+dy*Math.cos(a)}}function handleAt(o,x,y){const p=localPoint(o,x,y),m=18/state.zoom,hs=12/state.zoom;if(Math.abs(p.x-o.w/2)<m&&Math.abs(p.y-o.h/2)<m)return"se";if(Math.abs(p.x+o.w/2)<m&&Math.abs(p.y-o.h/2)<m)return"sw";if(Math.abs(p.x-o.w/2)<m&&Math.abs(p.y+o.h/2)<m)return"ne";if(Math.abs(p.x+o.w/2)<m&&Math.abs(p.y+o.h/2)<m)return"nw";if(Math.abs(p.x)<m&&Math.abs(p.y+o.h/2)<m)return"n";if(Math.abs(p.x)<m&&Math.abs(p.y-o.h/2)<m)return"s";if(Math.abs(p.x-o.w/2)<m&&Math.abs(p.y)<m)return"e";if(Math.abs(p.x+o.w/2)<m&&Math.abs(p.y)<m)return"w";if(Math.abs(p.x)<hs&&Math.abs(p.y+o.h/2-48/state.zoom)<m)return"rotate";return null}function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*state.width/r.width,y:(e.clientY-r.top)*state.height/r.height}}
function hit(o,x,y){const dx=x-o.x,dy=y-o.y,a=-(o.rotation||0)*Math.PI/180,rx=dx*Math.cos(a)-dy*Math.sin(a),ry=dx*Math.sin(a)+dy*Math.cos(a);if(o.type==="circle")return(rx/(o.w/2))**2+(ry/(o.h/2))**2<=1;return Math.abs(rx)<=o.w/2&&Math.abs(ry)<=o.h/2}
function base(type,x,y){return{id:uid(),type,x,y,w:300,h:180,rotation:0,opacity:1,fill:"#7c5cff",stroke:"#000000",strokeWidth:0,radius:24}}
function select(x,y,additive=false){for(let i=state.objects.length-1;i>=0;i--)if(hit(state.objects[i],x,y)){const id=state.objects[i].id;if(additive){const a=state.selectedIds.includes(id);state.selectedIds=a?state.selectedIds.filter(v=>v!==id):[...state.selectedIds,id];state.selected=state.selectedIds.at(-1)||null}else{state.selected=id;state.selectedIds=[id]}render();ui();return}if(!additive){state.selected=null;state.selectedIds=[];render();ui()}}
function add(x,y){if(state.tool==="select"){select(x,y);return}if(state.tool==="image"){$("#imageInput").click();return}const o=base(state.tool,x,y);if(state.tool==="text"){Object.assign(o,{w:430,h:120,text:"Your text",fontSize:64,fontFamily:"system-ui",weight:750,italic:false,lineHeight:1.18,letterSpacing:0,align:"center",fill:"#17131f"})}if(state.tool==="circle"){o.w=o.h=190;o.fill="#ff6f91"}if(state.tool==="line"){o.w=360;o.h=10;o.fill="#17131f";o.stroke="#17131f";o.strokeWidth=10}commit();state.objects.push(o);state.selected=o.id;state.tool="select";active();render();ui()}
function active(){$$(".tool").forEach(b=>b.classList.toggle("active",b.dataset.tool===state.tool))}
function name(o){return o.type==="text"?o.text.slice(0,24)||"Text":o.type[0].toUpperCase()+o.type.slice(1)}
function esc(s){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function ui(){props();layers();$("#deleteSelected").disabled=!state.selected;$("#duplicateSelected").disabled=!state.selected;historyButtons()}
function props(){const h=$("#properties"),o=state.objects.find(x=>x.id===state.selected);if(!o){h.innerHTML='<div class="empty-state">Select an object to edit its properties.</div>';return}let s='<div class="prop-grid"><div class="prop"><label>X</label><input data-p="x" type="number" value="'+Math.round(o.x)+'"></div><div class="prop"><label>Y</label><input data-p="y" type="number" value="'+Math.round(o.y)+'"></div><div class="prop"><label>Width</label><input data-p="w" type="number" min="1" value="'+Math.round(o.w)+'"></div><div class="prop"><label>Height</label><input data-p="h" type="number" min="1" value="'+Math.round(o.h)+'"></div><div class="prop"><label>Rotation</label><input data-p="rotation" type="number" value="'+Math.round(o.rotation||0)+'"></div><div class="prop"><label>Opacity</label><input data-p="opacity" type="number" min="0" max="1" step=".05" value="'+(o.opacity??1)+'"></div></div>';
if(o.type==="text")s+='<div class="prop"><label>Text</label><textarea class="text-area" data-p="text">'+esc(o.text)+'</textarea></div><div class="prop-grid"><div class="prop"><label>Font</label><select data-p="fontFamily"><option>system-ui</option><option>Arial</option><option>Georgia</option><option>Verdana</option><option>Trebuchet MS</option><option>Courier New</option></select></div><div class="prop"><label>Font size</label><input data-p="fontSize" type="number" min="8" value="'+o.fontSize+'"></div><div class="prop"><label>Weight</label><select data-p="weight"><option value="400">Regular</option><option value="600">Semibold</option><option value="750">Bold</option><option value="900">Black</option></select></div><div class="prop"><label>Style</label><select data-p="italic"><option value="false">Normal</option><option value="true">Italic</option></select></div><div class="prop"><label>Align</label><select data-p="align"><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></div><div class="prop"><label>Line height</label><input data-p="lineHeight" type="number" min=".8" max="3" step=".05" value="'+(o.lineHeight||1.18)+'"></div><div class="prop"><label>Letter spacing</label><input data-p="letterSpacing" type="number" step=".5" value="'+(o.letterSpacing||0)+'"></div><div class="prop wide"><label>Text color</label><input data-p="fill" type="color" value="'+o.fill+'"></div></div>';
else if(o.type==="image")s+='<div class="prop-grid"><div class="prop wide"><label>Image fit</label><select data-p="fit"><option value="fill">Fill</option><option value="contain">Contain</option></select></div><div class="prop"><label>Opacity</label><input data-p="opacity" type="number" min="0" max="1" step=".05" value="'+(o.opacity??1)+'"></div><div class="prop wide"><label>Filter</label><select data-p="filter"><option value="none">Original</option><option value="grayscale(1)">Grayscale</option><option value="sepia(1)">Sepia</option><option value="contrast(1.25)">High contrast</option><option value="brightness(1.2)">Bright</option></select></div></div>';else if(o.type==="line")s+='<div class="prop-grid"><div class="prop"><label>Color</label><input data-p="stroke" type="color" value="'+(o.stroke||o.fill)+'"></div><div class="prop"><label>Thickness</label><input data-p="strokeWidth" type="number" min="1" value="'+o.strokeWidth+'"></div></div>';
else s+='<div class="prop-grid"><div class="prop"><label>Fill</label><input data-p="fill" type="color" value="'+o.fill+'"></div><div class="prop"><label>Radius</label><input data-p="radius" type="number" min="0" value="'+(o.radius||0)+'"></div><div class="prop"><label>Stroke</label><input data-p="stroke" type="color" value="'+(o.stroke||"#000000")+'"></div><div class="prop"><label>Stroke width</label><input data-p="strokeWidth" type="number" min="0" value="'+(o.strokeWidth||0)+'"></div></div>';
h.innerHTML=s;const w=h.querySelector('[data-p="weight"]');if(w)w.value=o.weight;const it=h.querySelector('[data-p="italic"]');if(it)it.value=String(!!o.italic);const al=h.querySelector('[data-p="align"]');if(al)al.value=o.align||"center";const ff=h.querySelector('[data-p="fontFamily"]');if(ff)ff.value=o.fontFamily||"system-ui";h.querySelectorAll("[data-p]").forEach(el=>el.onchange=()=>{let v=el.value;if(["x","y","w","h","rotation","opacity","fontSize","strokeWidth","radius","weight","lineHeight","letterSpacing"].includes(el.dataset.p))v=Number(v);commit();o[el.dataset.p]=v;render();ui()})}
function layers(){const h=$("#layers");h.innerHTML="";[...state.objects].reverse().forEach(o=>{const r=document.createElement("div");r.className="layer"+(o.id===state.selected?" selected":"");r.innerHTML='<span class="layer-icon">'+(o.type==="text"?"T":o.type==="image"?"▧":o.type==="circle"?"●":"▰")+'</span><span class="layer-name"></span><button title="Move up">↑</button><button title="Move down">↓</button>';r.querySelector(".layer-name").textContent=name(o);r.onclick=e=>{if(e.target.tagName!=="BUTTON"){state.selected=o.id;render();ui()}};const b=r.querySelectorAll("button");b[0].onclick=()=>move(o.id,1);b[1].onclick=()=>move(o.id,-1);h.appendChild(r)})}
function move(id,d){const i=state.objects.findIndex(o=>o.id===id),j=i+d;if(i<0||j<0||j>=state.objects.length)return;commit();[state.objects[i],state.objects[j]]=[state.objects[j],state.objects[i]];render();ui()}
function selectedObjects(){return state.objects.filter(o=>state.selectedIds.includes(o.id)||(state.selectedIds.length===0&&o.id===state.selected))}function align(mode){const a=selectedObjects();if(!a.length)return;commit();for(const o of a){if(mode==="left")o.x=o.w/2;if(mode==="center")o.x=state.width/2;if(mode==="right")o.x=state.width-o.w/2;if(mode==="top")o.y=o.h/2;if(mode==="middle")o.y=state.height/2;if(mode==="bottom")o.y=state.height-o.h/2}render();ui()}function centerSelected(){align("center");align("middle")}
function importProject(data){if(!data||data.app!=="Universal Graphics Designer")return alert("This is not a Universal Graphics Designer project.");commit();state.width=Math.max(1,Math.min(4000,Number(data.width)||1080));state.height=Math.max(1,Math.min(4000,Number(data.height)||1080));state.bg=data.bg||"#ffffff";state.objects=Array.isArray(data.objects)?data.objects.map(o=>({...o,id:o.id||uid()})):[];state.selected=null;resize();fit();render();ui()}
function snapMove(o,x,y){const t=8;let sx=null,sy=null;state.guides=[];if(Math.abs(x-state.width/2)<t){x=state.width/2;sx=state.width/2}if(Math.abs(y-state.height/2)<t){y=state.height/2;sy=state.height/2}for(const q of state.objects){if(q.id===o.id)continue;if(Math.abs(x-q.x)<t){x=q.x;sx=q.x}if(Math.abs(y-q.y)<t){y=q.y;sy=q.y}}if(sx!==null)state.guides.push({axis:"x",value:sx});if(sy!==null)state.guides.push({axis:"y",value:sy});return{x,y}}function nudge(dx,dy){const o=state.objects.find(x=>x.id===state.selected);if(!o)return;commit();o.x+=dx;o.y+=dy;render();ui()}
let clipboard=null;function duplicate(){const o=state.objects.find(x=>x.id===state.selected);if(!o)return;commit();const c=JSON.parse(JSON.stringify(o));c.id=uid();c.x+=30;c.y+=30;if(o.type==="image")c.image=o.image;state.objects.push(c);state.selected=c.id;state.selectedIds=[c.id];render();ui()}
function del(){if(!state.selected)return;commit();state.objects=state.objects.filter(o=>o.id!==state.selected);state.selected=null;render();ui()}
function historyButtons(){$("#undo").disabled=!state.history.length;$("#redo").disabled=!state.future.length}
function download(name,type,data){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function project(){return JSON.stringify({version:1,app:"Universal Graphics Designer",width:state.width,height:state.height,bg:state.bg,objects:state.objects.map(o=>{const c={...o};delete c.image;return c})},null,2)}
function png(){const a=document.createElement("a");a.download="universal-design.png";a.href=canvas.toDataURL("image/png");a.click()}
function svg(){const E=s=>esc(s),els=state.objects.map(o=>{const tr="translate("+o.x+" "+o.y+") rotate("+o.rotation+")";if(o.type==="rect")return'<rect transform="'+tr+'" x="'+(-o.w/2)+'" y="'+(-o.h/2)+'" width="'+o.w+'" height="'+o.h+'" rx="'+(o.radius||0)+'" fill="'+E(o.fill)+'" opacity="'+(o.opacity??1)+'" />';if(o.type==="circle")return'<ellipse transform="'+tr+'" rx="'+o.w/2+'" ry="'+o.h/2+'" fill="'+E(o.fill)+'" opacity="'+(o.opacity??1)+'" />';if(o.type==="line")return'<line transform="'+tr+'" x1="'+(-o.w/2)+'" x2="'+o.w/2+'" y1="0" y2="0" stroke="'+E(o.stroke||o.fill)+'" stroke-width="'+o.strokeWidth+'" stroke-linecap="round" />';if(o.type==="text")return'<text transform="'+tr+'" x="0" y="0" text-anchor="middle" dominant-baseline="middle" fill="'+E(o.fill)+'" font-family="'+E(o.fontFamily)+'" font-size="'+o.fontSize+'" font-weight="'+o.weight+'">'+E(o.text)+'</text>';return""}).join("");download("universal-design.svg","image/svg+xml",'<?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg" width="'+state.width+'" height="'+state.height+'" viewBox="0 0 '+state.width+' '+state.height+'"><rect width="100%" height="100%" fill="'+state.bg+'"/>'+els+"</svg>")}
function template(k){commit();state.objects=[];state.selected=null;if(k==="poster"){state.bg="#17132b";state.objects=[{...base("circle",860,220),id:uid(),w:360,h:360,fill:"#ff6f91",opacity:.75},{...base("rect",300,850),id:uid(),w:470,h:260,fill:"#7c5cff",radius:44},{...base("text",540,360),id:uid(),w:850,h:260,text:"MAKE\nSOMETHING\nBRILLIANT",fontSize:104,fontFamily:"system-ui",weight:900,fill:"#fff"},{...base("text",540,790),id:uid(),w:780,h:100,text:"Universal Graphics Designer",fontSize:36,fontFamily:"system-ui",weight:600,fill:"#d9d3ff"}]};else if(k==="quote"){state.bg="#f6f1e8";state.objects=[{...base("circle",120,120),id:uid(),w:150,h:150,fill:"#f4a261"},{...base("text",540,470),id:uid(),w:820,h:360,text:"Create boldly.\nShare freely.",fontSize:82,fontFamily:"Georgia",weight:700,fill:"#222"},{...base("text",540,760),id:uid(),w:700,h:80,text:"— Universal Graphics Designer",fontSize:28,fontFamily:"system-ui",weight:600,fill:"#675f56"}]};else if(k==="announcement"){state.bg="#fff";state.objects=[{...base("rect",540,180),id:uid(),w:920,h:220,fill:"#17131f",radius:36},{...base("text",540,180),id:uid(),w:820,h:150,text:"BIG NEWS",fontSize:92,fontFamily:"system-ui",weight:900,fill:"#fff"},{...base("text",540,470),id:uid(),w:820,h:300,text:"Your idea deserves\na beautiful canvas.",fontSize:66,fontFamily:"system-ui",weight:800,fill:"#17131f"},{...base("circle",900,900),id:uid(),w:240,h:240,fill:"#7c5cff"}]};state.selected=state.objects.at(-1)?.id||null;resize();fit();render();ui()}
canvas.addEventListener("pointerdown",e=>{const p=point(e);if(state.tool!=="select"){add(p.x,p.y);return}const o=[...state.objects].reverse().find(x=>hit(x,p.x,p.y));if(!o){state.selected=null;render();ui();return}state.selected=o.id;const h=handleAt(o,p.x,p.y);state.drag={id:o.id,x:p.x,y:p.y,ox:o.x,oy:o.y,ow:o.w,oh:o.h,or:o.rotation||0,handle:h,moved:false};canvas.setPointerCapture?.(e.pointerId);render();ui()});
canvas.addEventListener("pointermove",e=>{if(!state.drag)return;const p=point(e),d=state.drag,o=state.objects.find(x=>x.id===d.id);if(!o)return;const dx=p.x-d.x,dy=p.y-d.y;if(Math.abs(dx)+Math.abs(dy)>3&&!d.moved){commit();d.moved=true}if(d.moved){if(d.handle==="rotate"){o.rotation=d.or+Math.atan2(p.y-o.y,p.x-o.x)*180/Math.PI+90-Math.atan2(d.y-o.y,d.x-o.x)*180/Math.PI}else if(d.handle){const lp=localPoint(o,p.x,p.y),ox=localPoint(o,d.x,d.y);let nw=d.ow,nh=d.oh;if(d.handle.includes("e"))nw=Math.max(20,d.ow+(lp.x-ox.x)*2);if(d.handle.includes("w")){nw=Math.max(20,d.ow-(lp.x-ox.x)*2);o.x=d.ox+(lp.x-ox.x)}if(d.handle.includes("s"))nh=Math.max(20,d.oh+(lp.y-ox.y)*2);if(d.handle.includes("n")){nh=Math.max(20,d.oh-(lp.y-ox.y)*2);o.y=d.oy+(lp.y-ox.y)}if(d.handle==="n"||d.handle==="s"){o.h=nh}else if(d.handle==="e"||d.handle==="w"){o.w=nw}else{o.w=nw;o.h=nh}}else{const q=snapMove(o,d.ox+dx,d.oy+dy);o.x=q.x;o.y=q.y}render();ui()}});
canvas.addEventListener("pointerup",()=>{state.drag=null;state.guides=[];render()});
canvas.addEventListener("dblclick",e=>{const p=point(e),o=[...state.objects].reverse().find(x=>x.type==="text"&&hit(x,p.x,p.y));if(!o)return;const t=prompt("Edit text",o.text);if(t!==null&&t!==o.text){commit();o.text=t;render();ui()}});
$("#imageInput").onchange=e=>{const f=e.target.files[0];if(!f)return;const url=URL.createObjectURL(f),im=new Image;im.onload=()=>{const scale=Math.min(800/im.width,600/im.height,1),o=base("image",state.width/2,state.height/2);o.w=im.width*scale;o.h=im.height*scale;o.src=url;o.image=im;commit();state.objects.push(o);state.selected=o.id;state.tool="select";active();render();ui()};im.src=url;e.target.value=""};
$$(".tool").forEach(b=>b.onclick=()=>{state.tool=b.dataset.tool;active();$("#status").textContent=state.tool==="select"?"Select an object or choose a tool.":"Tap the canvas to place "+state.tool+".";if(state.tool==="image")$("#imageInput").click()});
$("#alignLeft").onclick=()=>align("left");$("#alignCenter").onclick=()=>align("center");$("#alignRight").onclick=()=>align("right");$("#alignTop").onclick=()=>align("top");$("#alignMiddle").onclick=()=>align("middle");$("#alignBottom").onclick=()=>align("bottom");$("#undo").onclick=undo;$("#redo").onclick=redo;$("#centerSelected").onclick=centerSelected;$("#duplicateSelected").onclick=duplicate;$("#deleteSelected").onclick=del;$("#clearAll").onclick=()=>{if(state.objects.length){commit();state.objects=[];state.selected=null;render();ui()}};
$("#bgColor").onchange=e=>{commit();state.bg=e.target.value;render()};$("#zoom").oninput=e=>zoom(e.target.value/100);$("#zoomIn").onclick=()=>zoom(state.zoom+.1);$("#zoomOut").onclick=()=>zoom(state.zoom-.1);$("#fitCanvas").onclick=fit;
$("#canvasSize").onchange=e=>{if(e.target.value==="custom"){const w=Number(prompt("Canvas width (px)",state.width)),h=Number(prompt("Canvas height (px)",state.height));if(w>0&&h>0){commit();state.width=Math.min(4000,w);state.height=Math.min(4000,h);resize();fit();render()}return}const [w,h]=e.target.value.split("x").map(Number);commit();state.width=w;state.height=h;resize();fit();render()};
$$("[data-template]").forEach(b=>b.onclick=()=>template(b.dataset.template));
$("#saveProject").onclick=()=>download("universal-design.json","application/json",project());$("#openProject").onclick=()=>$("#projectInput").click();$("#projectInput").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader;r.onload=()=>{try{importProject(JSON.parse(r.result))}catch(err){alert("Could not open this project.")}};r.readAsText(f);e.target.value=""};$("#exportBtn").onclick=()=>$("#exportDialog").showModal();
$$("[data-export]").forEach(b=>b.onclick=()=>setTimeout(()=>{const k=b.dataset.export;if(k==="png")png();if(k==="svg")svg();if(k==="project")download("universal-design.json","application/json",project())},0));
$("#helpBtn").onclick=()=>$("#helpDialog").showModal();$("#closeHelp").onclick=()=>$("#helpDialog").close();
document.addEventListener("keydown",e=>{if(["INPUT","TEXTAREA","SELECT"].includes(document.activeElement.tagName))return;const k=e.key.toLowerCase();if((e.ctrlKey||e.metaKey)&&k==="z"){e.preventDefault();undo();return}if((e.ctrlKey||e.metaKey)&&k==="y"){e.preventDefault();redo();return}if((e.ctrlKey||e.metaKey)&&k==="d"){e.preventDefault();duplicate();return}if((e.ctrlKey||e.metaKey)&&k==="c"){const a=selectedObjects();clipboard=a.map(o=>{const c=JSON.parse(JSON.stringify(o));delete c.image;return c});return}if((e.ctrlKey||e.metaKey)&&k==="v"){if(clipboard?.length){commit();const added=clipboard.map(o=>({...o,id:uid(),x:o.x+30,y:o.y+30}));state.objects.push(...added);state.selected=added.at(-1).id;state.selectedIds=added.map(o=>o.id);render();ui()}return}if(k==="delete"||k==="backspace"){del();return}if(["arrowup","arrowdown","arrowleft","arrowright"].includes(e.key)){e.preventDefault();const d=e.shiftKey?10:1;nudge(e.key==="arrowleft"?-d:e.key==="arrowright"?d:0,e.key==="arrowup"?-d:e.key==="arrowdown"?d:0);return}if(k==="escape"){state.selected=null;state.selectedIds=[];render();ui();return}const m={v:"select",t:"text",r:"rect",c:"circle",i:"image"};if(m[k]){$(".tool[data-tool='"+m[k]+"']").click()}});
window.addEventListener("resize",()=>fit());resize();fit();render();ui();
})();